language: ruby
rvm:
  - 2.3.8
  - 2.5.3
  - 2.6.1
  - ruby-head
before_script:
  - git config --global user.email "travis-ci@digitpaint.nl"
  - git config --global user.name "Travis-CI"
after_success:
  - bundle exec codeclimate-test-reporter
matrix:
  fast_finish: true
env:
  global:
    secure: eMPdp74VWvC6r7CSzN06FEMf5Wq9AfxqIgjfr4Z4AMxUsehApSJe1y/blaqN6XcpLK4TYw4bwzRUjAzUjOMMW5aJ4Kr1nrW2k6bJehbubhkkPfDxcc+NzYUZ+oxqbPMOZP6zQoSRRd5rhY2qd3xVkKecK1KZOxlA1/pce6y15YU=
