language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - 2.2.2
before_script:
  - git config --global user.email "travis-ci@digitpaint.nl"
  - git config --global user.name "Travis-CI"
matrix:
  fast_finish: true