# Ruby
# Package your Ruby application.
# Add steps that install rails, analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/ruby

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.5'

- script: choco install zip -y
  displayName: 'Install zip command using chocolatey'

- script: |
    git config --global user.email "foo@example.com"
    git config --global user.name "Foo Bar"
  displayName: 'Configure Git for tests that call out to Git'

- script: gem install bundler
  displayName: 'gem install bundler'

- script: |
    bundle install --retry=3 --jobs=4
  displayName: 'bundle install'

- script: bundle exec rake
  displayName: 'bundle exec rake'

